version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Lobby_MS
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3316:3306"
  webapp:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/railsapi
    ports:
      - "3010:3000"
    depends_on:
      - db
    environment:
      DB_USER: root
      DB_NAME: Lobby_MS
      DB_PASSWORD: root
      DB_HOST: db