version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Lobby_MS
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3308:3306"
  app:
    build: . 
    command: bundle exec rails s -p 4010 -b '0.0.0.0'
    volumes:
      - ".:/Lobby_MS"
    ports:
      - "4010:4010"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: root
      DB_NAME: Lobby_MS
      DB_PASSWORD: root
      DB_HOST: db